### ISSUE TITLE
[Bug] AttributeObserverCleanup can not add to Entity During baking.

### ISSUE THREAD

**Issue by filod** [PhilSA/Trove#2]
https://github.com/PhilSA/Trove/blob/ec52e69dc9e982bcadd97bd38c43b6eea67d1916/com.trove.attributes/Runtime/AttributeUtilities.cs#L49

this can cause AddModifier using AttributeCommand fail

(don't know why unity ecs can not bake ICleanupBufferElementData but with no error message when you do it)

**Comment by PhilSA** [comment]
Hey, thanks for reporting this. This case wasn't caught by my tests, and it's quite important.

I've been thinking of an elegant solution for this, but without being able to bake cleanup components, this is a pretty tough problem. I did find a solution that I've pushed to Trove v0.2.0, but that solution isn't perfect. In short:
- There no longer is a cleanup component on attribute-owning entities. So the baking will work now
- In order to replace what this cleanup component was doing, users must now call a function on attribute-owning entities to make sure that all other attributes that observe them get properly recalculated post-destruction 

Here's a new documentation page that explains how to deal with destroying attribute-owning entities:
https://github.com/PhilSA/Trove/blob/v0.2.0/com.trove.attributes/Documentation~/how-it-works-destruction.md
